import { useRouter } from "next/router";
import Head from 'next/head'
import { Header } from "../../components/Header";
import { Footer } from "../../components/Footer";

export default function PokemonDetails() {

    const router = useRouter();

    console.log("rota", router.query.name);

    return (
        <div>
            <Head>
                <title>Pokédexmon | {router.query.name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9645579603385719" crossOrigin="anonymous"></script>
            </Head>

            <Header />
            <Footer />
        </div>
    )
}