import Head from 'next/head'
import { Footer } from '../components/Footer'
import { Header } from '../components/Header'
import { PokemonList } from '../components/PokemonList'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pokédexmon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <PokemonList />
      <Footer />

    </div>
  )
}
