import Head from 'next/head'
import { Ads } from '../components/Ads'
import { Footer } from '../components/Footer'
import { Header } from '../components/Header'
import { PokemonList } from '../components/PokemonList'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pokédexmon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9645579603385719" crossOrigin="anonymous"></script>
      </Head>

      <Header />
      <Ads />
      <PokemonList />
      <Ads />
      <Footer />

    </div>
  )
}
